# Generated by Django 2.1.7 on 2019-03-29 20:26

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('tvshows', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='tvshows',
            managers=[
                ('tv_shows_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('user_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='tvshows',
            name='status',
            field=models.CharField(choices=[('3', 'Cancelled'), ('2', 'Finished'), ('1', 'Ongoing')], max_length=2),
        ),
    ]
