# Generated by Django 2.1.7 on 2019-03-29 20:29

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('tvshows', '0002_auto_20190329_2026'),
    ]

    operations = [
        migrations.CreateModel(
            name='TVShow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('genre', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('2', 'Finished'), ('3', 'Cancelled'), ('1', 'Ongoing')], max_length=2)),
                ('num_episodes', models.IntegerField()),
            ],
            managers=[
                ('tv_shows_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.DeleteModel(
            name='tvshows',
        ),
    ]
