# Generated by Django 2.1.7 on 2019-03-29 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvshows', '0003_auto_20190329_2029'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='tvshow',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='tvshow',
            name='status',
            field=models.CharField(choices=[('1', 'Ongoing'), ('3', 'Cancelled'), ('2', 'Finished')], max_length=2),
        ),
    ]
