# Generated by Django 2.1.7 on 2019-03-29 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvshows', '0004_auto_20190329_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tvshow',
            name='status',
            field=models.CharField(choices=[('3', 'Cancelled'), ('2', 'Finished'), ('1', 'Ongoing')], max_length=2),
        ),
    ]
